### ISSUE TITLE
Still active?

### ISSUE THREAD

**Issue by wolframhaussig** [AntMeNet/AntMeCore#53]
Hi, I really liked Antme 1.x and am really excited for Antme 2 but I see no updates anymore. Is this project still active?

**Comment by susch19** [comment]
Yes this project is still active, but the work on it has slowed down by a lot. With the normal work and work on AntMe 1 the time that can be worked on v2 is limited. Also, according to tom, he often develops things, without pushing it, because the changes are not finished.

**Comment by patteki** [comment]
First, happy new Year!!! 
As @susch19 already mentioned this project is NOT dead, but in a hibernating state, I would call it.
So don't expect any feature updates or mayor releases soon.

Patrick
